/* =======================================================================
   DROP & CREATE FULL SCHEMA  (UPPER-CASE IDENTIFIERS)
   ======================================================================= */

-- ---------- ENUM -------------------------------------------------------
DROP TYPE IF EXISTS RUOLO_ENUM CASCADE;
CREATE TYPE RUOLO_ENUM AS ENUM ('REG','BOA','BOE');   -- VIS = anonimo

-- ---------- LINEA ------------------------------------------------------
DROP TABLE IF EXISTS LINEA CASCADE;
CREATE TABLE LINEA (
    ID_LINEA      SERIAL PRIMARY KEY,
    LUNGHEZZA_KM  NUMERIC(6,2) NOT NULL CHECK (LUNGHEZZA_KM > 0)
);

/* ---------- TIPO / MATERIALE ROTABILE --------------------------------- */
DROP TABLE IF EXISTS TIPO_MATERIALE_ROTABILE CASCADE;
CREATE TABLE TIPO_MATERIALE_ROTABILE (
    ID_TIPO      SERIAL PRIMARY KEY,
    SIGLA_SERIE  TEXT NOT NULL UNIQUE,
    CATEGORIA    TEXT,
    SEDUTE       SMALLINT CHECK (SEDUTE > 0)
);

DROP TABLE IF EXISTS MATERIALE_ROTABILE CASCADE;
CREATE TABLE MATERIALE_ROTABILE (
    ID_MATERIALE        SERIAL PRIMARY KEY,
    ID_TIPO_MATERIALE   INT  NOT NULL REFERENCES TIPO_MATERIALE_ROTABILE(ID_TIPO),
    NUM_POSTO           SMALLINT,
    CODICE_PROGRESSIVO  TEXT UNIQUE,
    DATA_MANUTENZIONE   DATE
);
CREATE INDEX IDX_ROTABILE_TIPO ON MATERIALE_ROTABILE(ID_TIPO_MATERIALE);

/* ---------- UTENTE ----------------------------------------------------- */
DROP TABLE IF EXISTS UTENTE CASCADE;
CREATE TABLE UTENTE (
    ID_UTENTE      SERIAL PRIMARY KEY,
    NOME           TEXT,
    COGNOME        TEXT,
    EMAIL          TEXT UNIQUE NOT NULL,
    HASH_PWD       TEXT NOT NULL,
    CELLULARE      VARCHAR(15),
    DATA_NASCITA   DATE,
    LUOGO_NASCITA  TEXT,
    RUOLO          RUOLO_ENUM NOT NULL DEFAULT 'REG'
);
CREATE INDEX IDX_UTENTE_RUOLO ON UTENTE(RUOLO);

/* ---------- STAZIONE --------------------------------------------------- */
DROP TABLE IF EXISTS STAZIONE CASCADE;
CREATE TABLE STAZIONE (
    ID_STAZIONE   SERIAL PRIMARY KEY,
    NOME          TEXT NOT NULL,
    KM            NUMERIC(7,2) CHECK (KM >= 0),
    ID_LINEA      INT NOT NULL REFERENCES LINEA(ID_LINEA)
);
CREATE INDEX IDX_STAZIONE_LINEA ON STAZIONE(ID_LINEA);

/* ---------- SUB_TRATTA ------------------------------------------------- */
DROP TABLE IF EXISTS SUB_TRATTA CASCADE;
CREATE TABLE SUB_TRATTA (
    ID_SUB_TRATTA       SERIAL PRIMARY KEY,
    ID_STAZIONE_ORIGINE INT NOT NULL REFERENCES STAZIONE(ID_STAZIONE),
    ID_STAZIONE_ARRIVO  INT NOT NULL REFERENCES STAZIONE(ID_STAZIONE),
    LUNGHEZZA_KM        NUMERIC(6,2) CHECK (LUNGHEZZA_KM > 0),
    VEL_MEDIA_KM        NUMERIC(5,2) CHECK (VEL_MEDIA_KM > 0)
);
CREATE INDEX IDX_SUBTRATTA_ORIGINE ON SUB_TRATTA(ID_STAZIONE_ORIGINE);
CREATE INDEX IDX_SUBTRATTA_ARRIVO  ON SUB_TRATTA(ID_STAZIONE_ARRIVO);

/* ---------- CONVOGLIO -------------------------------------------------- */
DROP TABLE IF EXISTS CONVOGLIO CASCADE;
CREATE TABLE CONVOGLIO (
    ID_CONVOGLIO           SERIAL PRIMARY KEY,
    NOME_CONVOGLIO         TEXT UNIQUE,
    ID_MATERIALE_ROTABILE  INT NOT NULL REFERENCES MATERIALE_ROTABILE(ID_MATERIALE),
    POSIZIONE_NEL_CONVOGLIO SMALLINT
);
CREATE INDEX IDX_CONVOGLIO_MAT ON CONVOGLIO(ID_MATERIALE_ROTABILE);

/* ---------- TRENO ------------------------------------------------------ */
DROP TABLE IF EXISTS TRENO CASCADE;
CREATE TABLE TRENO (
    ID_TRENO              SERIAL PRIMARY KEY,
    DATA                  DATE NOT NULL,
    CODICE_CORSA          TEXT UNIQUE,
    DIREZIONE_CORSA       TEXT,
    ID_CONVOGLIO          INT NOT NULL REFERENCES CONVOGLIO(ID_CONVOGLIO),
    ID_STAZIONE_PARTENZA  INT REFERENCES STAZIONE(ID_STAZIONE),
    ID_STAZIONE_ARRIVO    INT REFERENCES STAZIONE(ID_STAZIONE)
);
CREATE INDEX IDX_TRENO_CONVOGLIO ON TRENO(ID_CONVOGLIO);

/* ---------- CORSA_SUB_TRATTA (tabella ponte) --------------------------- */
DROP TABLE IF EXISTS CORSA_SUB_TRATTA CASCADE;
CREATE TABLE CORSA_SUB_TRATTA (
    ID_TRENO      INT REFERENCES TRENO(ID_TRENO) ON DELETE CASCADE,
    ID_SUB_TRATTA INT REFERENCES SUB_TRATTA(ID_SUB_TRATTA) ON DELETE CASCADE,
    T_START       TIME NOT NULL,
    T_END         TIME NOT NULL,
    DIREZIONE     TEXT,
    PRIMARY KEY (ID_TRENO, ID_SUB_TRATTA)
);
CREATE INDEX IDX_CORSA_SUB_TRATTA_SUB ON CORSA_SUB_TRATTA(ID_SUB_TRATTA);

/* ---------- TRACCIA_ORARIA --------------------------------------------- */
DROP TABLE IF EXISTS TRACCIA_ORARIA CASCADE;
CREATE TABLE TRACCIA_ORARIA (
    ID_TRACCIA_ORARIA SERIAL PRIMARY KEY,
    ID_STAZIONE       INT NOT NULL REFERENCES STAZIONE(ID_STAZIONE),
    ID_CORSA          INT NOT NULL REFERENCES TRENO(ID_TRENO),
    ORARIO_ARRIVO     TIME,
    ORARIO_PARTENZA   TIME,
    KM_CUMULATI       NUMERIC(7,2),
    VELOCITA          NUMERIC(5,2)
);
CREATE INDEX IDX_TRACCIA_STAZIONE ON TRACCIA_ORARIA(ID_STAZIONE);
CREATE INDEX IDX_TRACCIA_CORSA    ON TRACCIA_ORARIA(ID_CORSA);

/* ---------- BIGLIETTO --------------------------------------------------- */
DROP TABLE IF EXISTS BIGLIETTO CASCADE;
CREATE TABLE BIGLIETTO (
    ID_BIGLIETTO  SERIAL PRIMARY KEY,
    ID_UTENTE     INT NOT NULL REFERENCES UTENTE(ID_UTENTE),
    ID_CORSA      INT NOT NULL REFERENCES TRENO(ID_TRENO),
    ID_ROTABILE   INT REFERENCES MATERIALE_ROTABILE(ID_MATERIALE),
    NUM_POSTO     SMALLINT,
    DATA_ACQUISTO TIMESTAMP DEFAULT NOW(),
    PREZZO        NUMERIC(7,2),
    STATO         TEXT
);
CREATE INDEX IDX_BIGLIETTO_UTENTE ON BIGLIETTO(ID_UTENTE);
CREATE INDEX IDX_BIGLIETTO_CORSA  ON BIGLIETTO(ID_CORSA);
CREATE INDEX IDX_BIGLIETTO_ROTAB  ON BIGLIETTO(ID_ROTABILE);

/* =======================================================================
   VISTA MATERIALIZZATA: ORARI PUBBLICI
   ======================================================================= */
DROP MATERIALIZED VIEW IF EXISTS VISTA_ORARI_PUBBLICI;
CREATE MATERIALIZED VIEW VISTA_ORARI_PUBBLICI AS
SELECT
  T.ID_TRENO,
  S_ORIG.NOME AS STAZIONE_PARTENZA,
  S_DEST.NOME AS STAZIONE_ARRIVO,
  T.DATA,
  MIN(TOA.ORARIO_PARTENZA) AS ORARIO_PARTENZA,
  MAX(TOA.ORARIO_ARRIVO)   AS ORARIO_ARRIVO
FROM TRENO T
JOIN TRACCIA_ORARIA TOA ON TOA.ID_CORSA = T.ID_TRENO
JOIN STAZIONE S_ORIG    ON S_ORIG.ID_STAZIONE = T.ID_STAZIONE_PARTENZA
JOIN STAZIONE S_DEST    ON S_DEST.ID_STAZIONE = T.ID_STAZIONE_ARRIVO
GROUP BY T.ID_TRENO, S_ORIG.NOME, S_DEST.NOME, T.DATA
ORDER BY T.DATA, ORARIO_PARTENZA;

/* =======================================================================
   TRIGGER: REFRESH VISTA_ORARI_PUBBLICI
   ======================================================================= */
DROP FUNCTION IF EXISTS REFRESH_ORARI_PUBBLICI() CASCADE;
CREATE FUNCTION REFRESH_ORARI_PUBBLICI()
RETURNS TRIGGER AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY VISTA_ORARI_PUBBLICI;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_REFRESH_ORARI_PUBBLICI ON TRACCIA_ORARIA;
CREATE TRIGGER TRG_REFRESH_ORARI_PUBBLICI
AFTER INSERT OR UPDATE OR DELETE ON TRACCIA_ORARIA
FOR EACH STATEMENT
EXECUTE FUNCTION REFRESH_ORARI_PUBBLICI();