-- ================== CREAZIONE SCHEMA FERROVIE =========================
-- Data rigenerazione: 2025-07-19

-- ENUM ------------------------------------------------------------
DROP TYPE IF EXISTS RUOLO_ENUM CASCADE;
CREATE TYPE RUOLO_ENUM AS ENUM ('REG','BOA','BOE');

-- LINEA -----------------------------------------------------------
DROP TABLE IF EXISTS LINEA CASCADE;
CREATE TABLE LINEA (
  ID_LINEA SERIAL PRIMARY KEY,
  LUNGHEZZA_KM NUMERIC(6,2) NOT NULL CHECK (LUNGHEZZA_KM > 0)
);

-- STAZIONE --------------------------------------------------------
DROP TABLE IF EXISTS STAZIONE CASCADE;
CREATE TABLE STAZIONE (
  ID_STAZIONE SERIAL PRIMARY KEY,
  NOME TEXT NOT NULL,
  KM NUMERIC(7,2) CHECK (KM >= 0),
  ID_LINEA INT NOT NULL REFERENCES LINEA(ID_LINEA)
);

-- SUB_TRATTA ------------------------------------------------------
DROP TABLE IF EXISTS SUB_TRATTA CASCADE;
CREATE TABLE SUB_TRATTA (
  ID_SUB_TRATTA SERIAL PRIMARY KEY,
  ID_STAZIONE_ORIGINE INT NOT NULL REFERENCES STAZIONE(ID_STAZIONE),
  ID_STAZIONE_ARRIVO INT NOT NULL REFERENCES STAZIONE(ID_STAZIONE),
  LUNGHEZZA_KM NUMERIC(6,2) CHECK (LUNGHEZZA_KM > 0),
  VEL_MEDIA_KM NUMERIC(5,2) CHECK (VEL_MEDIA_KM > 0)
);

-- TIPO MATERIALE ROTABILE -----------------------------------------
DROP TABLE IF EXISTS TIPO_MATERIALE_ROTABILE CASCADE;
CREATE TABLE TIPO_MATERIALE_ROTABILE (
  ID_TIPO SERIAL PRIMARY KEY,
  SIGLA_SERIE TEXT NOT NULL UNIQUE,
  CATEGORIA TEXT,
  SEDUTE SMALLINT CHECK (SEDUTE > 0)
);

-- MATERIALE ROTABILE ----------------------------------------------
DROP TABLE IF EXISTS MATERIALE_ROTABILE CASCADE;
CREATE TABLE MATERIALE_ROTABILE (
  ID_MATERIALE SERIAL PRIMARY KEY,
  ID_TIPO_MATERIALE INT NOT NULL REFERENCES TIPO_MATERIALE_ROTABILE(ID_TIPO),
  NUM_POSTO SMALLINT,
  CODICE_PROGRESSIVO TEXT UNIQUE,
  DATA_MANUTENZIONE DATE
);

-- CONVOGLIO -------------------------------------------------------
DROP TABLE IF EXISTS CONVOGLIO CASCADE;
CREATE TABLE CONVOGLIO (
  ID_CONVOGLIO SERIAL PRIMARY KEY,
  NOME_CONVOGLIO TEXT UNIQUE,
  ID_MATERIALE_ROTABILE INT NOT NULL REFERENCES MATERIALE_ROTABILE(ID_MATERIALE),
  POSIZIONE_NEL_CONVOGLIO SMALLINT
);

-- UTENTE ----------------------------------------------------------
DROP TABLE IF EXISTS UTENTE CASCADE;
CREATE TABLE UTENTE (
  ID_UTENTE SERIAL PRIMARY KEY,
  NOME TEXT,
  COGNOME TEXT,
  EMAIL TEXT UNIQUE NOT NULL,
  HASH_PWD TEXT NOT NULL,
  CELLULARE VARCHAR(15),
  DATA_NASCITA DATE,
  LUOGO_NASCITA TEXT,
  RUOLO RUOLO_ENUM NOT NULL DEFAULT 'REG'
);

-- TRENO -----------------------------------------------------------
DROP TABLE IF EXISTS TRENO CASCADE;
CREATE TABLE TRENO (
  ID_TRENO SERIAL PRIMARY KEY,
  DATA DATE NOT NULL,
  CODICE_CORSA TEXT UNIQUE,
  DIREZIONE_CORSA TEXT,
  ID_CONVOGLIO INT NOT NULL REFERENCES CONVOGLIO(ID_CONVOGLIO),
  ID_STAZIONE_PARTENZA INT REFERENCES STAZIONE(ID_STAZIONE),
  ID_STAZIONE_ARRIVO INT REFERENCES STAZIONE(ID_STAZIONE)
);

-- CORSA_SUB_TRATTA ------------------------------------------------
DROP TABLE IF EXISTS CORSA_SUB_TRATTA CASCADE;
CREATE TABLE CORSA_SUB_TRATTA (
  ID_TRENO INT REFERENCES TRENO(ID_TRENO) ON DELETE CASCADE,
  ID_SUB_TRATTA INT REFERENCES SUB_TRATTA(ID_SUB_TRATTA) ON DELETE CASCADE,
  T_START TIME NOT NULL,
  T_END TIME NOT NULL,
  DIREZIONE TEXT,
  PRIMARY KEY (ID_TRENO, ID_SUB_TRATTA)
);

-- TRIGGER per evitare conflitto su binario unico
CREATE OR REPLACE FUNCTION chk_conflitto_subtratta()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM CORSA_SUB_TRATTA C
    WHERE C.ID_SUB_TRATTA = NEW.ID_SUB_TRATTA
      AND C.T_START < NEW.T_END
      AND C.T_END > NEW.T_START
  ) THEN
    RAISE EXCEPTION 'Conflitto orario su subtratta';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_chk_conflict ON CORSA_SUB_TRATTA;
CREATE TRIGGER trg_chk_conflict
BEFORE INSERT ON CORSA_SUB_TRATTA
FOR EACH ROW
EXECUTE FUNCTION chk_conflitto_subtratta();

-- TRIGGER per vincolo ripartenza convoglio da ultima stazione raggiunta
CREATE OR REPLACE FUNCTION chk_partenza_coerente()
RETURNS TRIGGER AS $$
DECLARE
  ultima_stazione INT;
BEGIN
  SELECT T2.ID_STAZIONE_ARRIVO
  INTO ultima_stazione
  FROM TRENO T2
  WHERE T2.ID_CONVOGLIO = NEW.ID_CONVOGLIO
    AND T2.DATA < NEW.DATA
  ORDER BY T2.DATA DESC
  LIMIT 1;

  IF ultima_stazione IS NOT NULL AND ultima_stazione <> NEW.ID_STAZIONE_PARTENZA THEN
    RAISE EXCEPTION 'Il convoglio deve ripartire dalla stazione dove era arrivato: % <> %', ultima_stazione, NEW.ID_STAZIONE_PARTENZA;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ripartenza_stazione ON TRENO;
CREATE TRIGGER trg_ripartenza_stazione
BEFORE INSERT ON TRENO
FOR EACH ROW
EXECUTE FUNCTION chk_partenza_coerente();

-- TRIGGER per evitare partenze contemporanee nella stessa direzione
CREATE OR REPLACE FUNCTION chk_partenza_stesso_orario()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM TRACCIA_ORARIA T
    JOIN TRENO R ON R.ID_TRENO = T.ID_CORSA
    WHERE T.ORARIO_PARTENZA = NEW.ORARIO_PARTENZA
      AND T.ID_STAZIONE = NEW.ID_STAZIONE
      AND R.DIREZIONE_CORSA = (SELECT DIREZIONE_CORSA FROM TRENO WHERE ID_TRENO = NEW.ID_CORSA)
  ) THEN
    RAISE EXCEPTION 'Partenza già presente nella stessa direzione da questa stazione e orario';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_stesso_orario_direzione ON TRACCIA_ORARIA;
CREATE TRIGGER trg_stesso_orario_direzione
BEFORE INSERT ON TRACCIA_ORARIA
FOR EACH ROW
EXECUTE FUNCTION chk_partenza_stesso_orario();

-- TRACCIA_ORARIA --------------------------------------------------
DROP TABLE IF EXISTS TRACCIA_ORARIA CASCADE;
CREATE TABLE TRACCIA_ORARIA (
  ID_TRACCIA_ORARIA SERIAL PRIMARY KEY,
  ID_STAZIONE INT NOT NULL REFERENCES STAZIONE(ID_STAZIONE),
  ID_CORSA INT NOT NULL REFERENCES TRENO(ID_TRENO),
  ORARIO_ARRIVO TIME,
  ORARIO_PARTENZA TIME,
  KM_CUMULATI NUMERIC(7,2),
  VELOCITA NUMERIC(5,2)
);

-- BIGLIETTO --------------------------------------------------------
DROP TABLE IF EXISTS BIGLIETTO CASCADE;
CREATE TABLE BIGLIETTO (
  ID_BIGLIETTO SERIAL PRIMARY KEY,
  ID_UTENTE INT NOT NULL REFERENCES UTENTE(ID_UTENTE),
  ID_CORSA INT NOT NULL REFERENCES TRENO(ID_TRENO),
  ID_ROTABILE INT REFERENCES MATERIALE_ROTABILE(ID_MATERIALE),
  NUM_POSTO SMALLINT,
  DATA_ACQUISTO TIMESTAMP DEFAULT NOW(),
  PREZZO NUMERIC(7,2),
  STATO TEXT,
  CONSTRAINT posti_non_superati CHECK (
    NUM_POSTO IS NULL
    OR (ID_CORSA IS NOT NULL AND NUM_POSTO <= (
      SELECT SUM(TMR.SEDUTE)
      FROM CONVOGLIO C
      JOIN TRENO T ON T.ID_CONVOGLIO = C.ID_CONVOGLIO
      JOIN MATERIALE_ROTABILE MR ON MR.ID_MATERIALE = C.ID_MATERIALE_ROTABILE
      JOIN TIPO_MATERIALE_ROTABILE TMR ON TMR.ID_TIPO = MR.ID_TIPO_MATERIALE
      WHERE T.ID_TRENO = BIGLIETTO.ID_CORSA
    ))
  )
);
